const STATS = {
    LOAD: 'STATS_LOAD',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_FAIL: 'STATS_LOAD_FAIL',
};

const VISITORS = {
    LOAD: 'VISITORS_LOAD',
    LOAD_SUCCESS: 'VISITORS_LOAD_SUCCESS',
    LOAD_FAIL: 'VISITORS_LOAD_FAIL',
};

export { STATS, VISITORS };
